name: Deployment
on:
  push:
    branches:
      - master
  workflow_dispatch: 
env:
  BUCKET: ${{ vars.BUCKET }}
  AWS_REGION: ${{ vars.AWS_REGION }}
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Load & Cache Dependencies
        uses: ./.github/actions/cache-deps
        with: 
          caching: 'false' # input in the composite action to not use the cache dependency
      - name: Output information
        run: echo "Cache used?" ${{ steps.cache-deps.outputs.used-cache  }}
      - name: Lint code
        run: npm run lint
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Load & Cache Dependencies
        uses: ./.github/actions/cache-deps
      - name: Test code
        id: run-tests
        run: npm run test
      - name: Upload test report
        if: failure() && steps.run-tests.outcome == 'failure'
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: test.json
  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Load & Cache Dependencies
        uses: ./.github/actions/cache-deps
      - name: Build website
        run: npm run build
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-files
          path: dist
  deploy:
    permissions:
      id-token: write # This is required for requesting the JWT
      contents: read  # This is required for actions/checkout
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Get build artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist-files
          path: ./dist
      - name: Output contents
        run: ls
      - name: Get AWS Permissions
        uses: aws-actions/configure-aws-credentials@v4
        with: 
          role-to-assume: arn:aws:iam::680226692656:role/GithubDemo1
          aws-region: ${{ env.AWS_REGION }}
      - name: Deploy site
        uses: ./.github/actions/deploy-s3-javascript
        with: 
          bucket: ${{ env.BUCKET }}
          dist-folder: ./dist
      - name: Output information
        run: | 
          echo "Live URL:" ${{ steps.deploy.outputs.website-url }}
  deploy-docker:
    permissions:
      id-token: write # This is required for requesting the JWT
      contents: read  # This is required for actions/checkout
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Get build artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist-files
          path: ./dist
      - name: Output contents
        run: ls
      - name: Get AWS Permissions
        uses: aws-actions/configure-aws-credentials@v4
        with: 
          role-to-assume: arn:aws:iam::680226692656:role/GithubDemo1
          aws-region: ${{ env.AWS_REGION }}
      - name: Deploy site
        uses: ./.github/actions/deploy-s3-docker
        with: 
          bucket: ${{ env.BUCKET }}
          dist-folder: ./dist
      - name: Output information
        run: | 
          echo "Live URL:" ${{ steps.deploy-docker.outputs.website-url }}